


export const products = [
    {
        id: 1,
        name: "Paracetamol 500mg",
        manufacturer: "Sun Pharma",
        pricePerUnit: 2.5,
        bulkDiscount: "10% off on 100+ units",
        stock: "In Stock",
        expiryDate: "2026-08-15",
        quantity: 1,
        category: "Painkillers",
        image: "/images/paracetamol.jpg",
    },
    {
        id: 2,
        name: "Amoxicillin 250mg",
        manufacturer: "Cipla Ltd",
        pricePerUnit: 5.0,
        bulkDiscount: "15% off on 50+ units",
        stock: "Limited",
        expiryDate: "2025-12-10",
        quantity: 1,
        category: "Antibiotics",
        image: "/images/amoxicillin.jpg",
    },
    {
        id: 3,
        name: "Cetirizine 10mg",
        manufacturer: "Dr. Reddy's",
        pricePerUnit: 1.8,
        bulkDiscount: "5% off on 200+ units",
        stock: "In Stock",
        expiryDate: "2027-03-22",
        quantity: 1,
        category: "Allergy",
        image: "/images/cetirizine.jpg",
    },
    {
        id: 4,
        name: "Aspirin 75mg",
        manufacturer: "Bayer",
        pricePerUnit: 3.2,
        bulkDiscount: "12% off on 150+ units",
        stock: "Out of Stock",
        expiryDate: "2025-07-01",
        quantity: 1,
        category: "Blood Thinner",
        image: "/images/aspirin.jpg",
    },
    {
        id: 5,
        name: "Metformin 500mg",
        manufacturer: "Glenmark",
        pricePerUnit: 6.0,
        bulkDiscount: "10% off on 100+ units",
        stock: "In Stock",
        expiryDate: "2026-05-30",
        quantity: 1,
        category: "Diabetes",
        image: "/images/metformin.jpg",
    },
    {
        id: 6,
        name: "Omeprazole 20mg",
        manufacturer: "Torrent Pharma",
        pricePerUnit: 4.5,
        bulkDiscount: "7% off on 120+ units",
        stock: "In Stock",
        expiryDate: "2026-10-20",
        quantity: 1,
        category: "Acidity",
        image: "/images/omeprazole.jpg",
    },
    {
        id: 7,
        name: "Losartan 50mg",
        manufacturer: "Lupin",
        pricePerUnit: 8.0,
        bulkDiscount: "10% off on 75+ units",
        stock: "Limited",
        expiryDate: "2026-12-15",
        quantity: 1,
        category: "Hypertension",
        image: "/images/losartan.jpg",
    },
    {
        id: 8,
        name: "Atorvastatin 10mg",
        manufacturer: "Mankind Pharma",
        pricePerUnit: 9.5,
        bulkDiscount: "8% off on 90+ units",
        stock: "In Stock",
        expiryDate: "2027-01-10",
        quantity: 1,
        category: "Cholesterol",
        image: "/images/atorvastatin.jpg",
    },
    {
        id: 9,
        name: "Dolo 650mg",
        manufacturer: "Micro Labs",
        pricePerUnit: 2.8,
        bulkDiscount: "5% off on 250+ units",
        stock: "In Stock",
        expiryDate: "2026-04-14",
        quantity: 1,
        category: "Fever & Pain",
        image: "/images/dolo.jpg",
    },
    {
        id: 10,
        name: "Ivermectin 12mg",
        manufacturer: "Hetero Drugs",
        pricePerUnit: 6.5,
        bulkDiscount: "15% off on 50+ units",
        stock: "Out of Stock",
        expiryDate: "2025-11-11",
        quantity: 1,
        category: "Anti-Parasitic",
        image: "/images/ivermectin.jpg",
    },
    {
        id: 11,
        name: "Azithromycin 500mg",
        manufacturer: "Aurobindo Pharma",
        pricePerUnit: 7.0,
        bulkDiscount: "12% off on 50+ units",
        stock: "In Stock",
        expiryDate: "2026-09-15",
        quantity: 1,
        category: "Antibiotics",
        image: "/images/azithromycin.jpg",
    },
    {
        id: 12,
        name: "Montelukast 10mg",
        manufacturer: "Glenmark Pharmaceuticals",
        pricePerUnit: 5.5,
        bulkDiscount: "10% off on 100+ units",
        stock: "Limited",
        expiryDate: "2026-07-20",
        quantity: 1,
        category: "Respiratory",
        image: "/images/montelukast.jpg",
    },
    {
        id: 13,
        name: "Ibuprofen 400mg",
        manufacturer: "Pfizer",
        pricePerUnit: 3.8,
        bulkDiscount: "8% off on 120+ units",
        stock: "In Stock",
        expiryDate: "2025-12-05",
        quantity: 1,
        category: "Pain Reliever",
        image: "/images/ibuprofen.jpg",
    },
    {
        id: 14,
        name: "Levocetirizine 5mg",
        manufacturer: "Alkem Labs",
        pricePerUnit: 2.2,
        bulkDiscount: "5% off on 200+ units",
        stock: "In Stock",
        expiryDate: "2027-06-10",
        quantity: 1,
        category: "Allergy",
        image: "/images/levocetirizine.jpg",
    },
    {
        id: 15,
        name: "Ranitidine 150mg",
        manufacturer: "Dr. Reddy's",
        pricePerUnit: 4.0,
        bulkDiscount: "10% off on 100+ units",
        stock: "Out of Stock",
        expiryDate: "2025-11-30",
        quantity: 1,
        category: "Acid Reflux",
        image: "/images/ranitidine.jpg",
    },
    {
        id: 16,
        name: "Amlodipine 5mg",
        manufacturer: "Zydus Cadila",
        pricePerUnit: 6.8,
        bulkDiscount: "10% off on 75+ units",
        stock: "In Stock",
        expiryDate: "2026-08-22",
        quantity: 1,
        category: "Blood Pressure",
        image: "/images/amlodipine.jpg",
    },
    {
        id: 17,
        name: "Cough Syrup 100ml",
        manufacturer: "Patanjali",
        pricePerUnit: 3.5,
        bulkDiscount: "5% off on 150+ units",
        stock: "In Stock",
        expiryDate: "2026-12-15",
        quantity: 1,
        category: "Cough & Cold",
        image: "/images/cough_syrup.jpg",
    },
    {
        id: 18,
        name: "Vitamin D3 60K",
        manufacturer: "Mankind Pharma",
        pricePerUnit: 8.5,
        bulkDiscount: "15% off on 50+ units",
        stock: "Limited",
        expiryDate: "2027-03-05",
        quantity: 1,
        category: "Vitamins & Supplements",
        image: "/images/vitamin_d3.jpg",
    },
    {
        id: 19,
        name: "Insulin Injection 10ml",
        manufacturer: "Novo Nordisk",
        pricePerUnit: 12.0,
        bulkDiscount: "10% off on 30+ units",
        stock: "In Stock",
        expiryDate: "2026-09-30",
        quantity: 1,
        category: "Diabetes",
        image: "/images/insulin.jpg",
    },
    {
        id: 20,
        name: "Thyroxine 50mcg",
        manufacturer: "Abbott",
        pricePerUnit: 4.2,
        bulkDiscount: "8% off on 90+ units",
        stock: "In Stock",
        expiryDate: "2027-04-18",
        quantity: 1,
        category: "Thyroid",
        image: "/images/thyroxine.jpg",
    },
    {
        id: 21,
        name: "Metformin 500mg",
        manufacturer: "USV Ltd.",
        pricePerUnit: 6.0,
        bulkDiscount: "10% off on 50+ units",
        stock: "In Stock",
        expiryDate: "2027-02-15",
        quantity: 1,
        category: "Diabetes",
        image: "/images/metformin.jpg",
    },
    {
        id: 22,
        name: "Omeprazole 20mg",
        manufacturer: "Cipla",
        pricePerUnit: 4.5,
        bulkDiscount: "12% off on 100+ units",
        stock: "Limited",
        expiryDate: "2026-08-10",
        quantity: 1,
        category: "Acid Reflux",
        image: "/images/omeprazole.jpg",
    },
    {
        id: 23,
        name: "Losartan 50mg",
        manufacturer: "Torrent Pharmaceuticals",
        pricePerUnit: 5.2,
        bulkDiscount: "8% off on 120+ units",
        stock: "In Stock",
        expiryDate: "2026-11-25",
        quantity: 1,
        category: "Blood Pressure",
        image: "/images/losartan.jpg",
    },
    {
        id: 24,
        name: "Cetirizine 10mg",
        manufacturer: "Dr. Reddy's",
        pricePerUnit: 2.0,
        bulkDiscount: "5% off on 200+ units",
        stock: "In Stock",
        expiryDate: "2027-07-15",
        quantity: 1,
        category: "Allergy",
        image: "/images/cetirizine.jpg",
    },
    {
        id: 25,
        name: "Amoxicillin 500mg",
        manufacturer: "Macleods Pharma",
        pricePerUnit: 7.5,
        bulkDiscount: "15% off on 75+ units",
        stock: "In Stock",
        expiryDate: "2026-09-30",
        quantity: 1,
        category: "Antibiotics",
        image: "/images/amoxicillin.jpg",
    },
    {
        id: 26,
        name: "Aspirin 75mg",
        manufacturer: "Sun Pharma",
        pricePerUnit: 3.8,
        bulkDiscount: "10% off on 90+ units",
        stock: "Limited",
        expiryDate: "2025-12-20",
        quantity: 1,
        category: "Heart Care",
        image: "/images/aspirin.jpg",
    },
    {
        id: 27,
        name: "Dolo 650mg",
        manufacturer: "Micro Labs",
        pricePerUnit: 5.0,
        bulkDiscount: "12% off on 50+ units",
        stock: "In Stock",
        expiryDate: "2027-01-05",
        quantity: 1,
        category: "Pain Reliever",
        image: "/images/dolo650.jpg",
    },
    {
        id: 28,
        name: "ORS (Oral Rehydration Solution)",
        manufacturer: "Himalaya",
        pricePerUnit: 2.5,
        bulkDiscount: "5% off on 200+ units",
        stock: "In Stock",
        expiryDate: "2026-10-12",
        quantity: 1,
        category: "Hydration",
        image: "/images/ors.jpg",
    },
    {
        id: 29,
        name: "Betadine Antiseptic Ointment",
        manufacturer: "Win-Medicare",
        pricePerUnit: 10.0,
        bulkDiscount: "10% off on 30+ units",
        stock: "In Stock",
        expiryDate: "2026-09-18",
        quantity: 1,
        category: "First Aid",
        image: "/images/betadine.jpg",
    },
    {
        id: 30,
        name: "Calcium & Vitamin D3 Tablets",
        manufacturer: "Mankind Pharma",
        pricePerUnit: 8.5,
        bulkDiscount: "15% off on 50+ units",
        stock: "Limited",
        expiryDate: "2027-03-08",
        quantity: 1,
        category: "Vitamins & Supplements",
        image: "/images/calcium_d3.jpg",
    },
];




export const moreProductsBatch4 = [
    {
        id: 41,
        name: "Paracetamol 650mg",
        manufacturer: "Cipla",
        pricePerUnit: 5.5,
        bulkDiscount: "10% off on 100+ units",
        stock: "In Stock",
        expiryDate: "2027-03-15",
        quantity: 1,
        category: "Pain Reliever",
        image: "/images/paracetamol.jpg",
        offers: {
            type: "Buy 1 Get 1 Free",
            description: "Get an extra strip free on purchasing 2 strips.",
        },
    },
    {
        id: 42,
        name: "Azithromycin 500mg",
        manufacturer: "Sun Pharma",
        pricePerUnit: 14.0,
        bulkDiscount: "15% off on 50+ units",
        stock: "Limited",
        expiryDate: "2026-09-20",
        quantity: 1,
        category: "Antibiotics",
        image: "/images/azithromycin.jpg",
        offers: {
            type: "Extra Discount",
            description: "Flat ₹50 off on orders above ₹500.",
        },
    },
    {
        id: 43,
        name: "Montelukast + Levocetirizine",
        manufacturer: "Glenmark",
        pricePerUnit: 12.5,
        bulkDiscount: "8% off on 75+ units",
        stock: "In Stock",
        expiryDate: "2026-12-10",
        quantity: 1,
        category: "Allergy & Asthma",
        image: "/images/montelukast.jpg",
        offers: {
            type: "Free Strips",
            description: "Buy 10 strips and get 1 free.",
        },
    },
    {
        id: 44,
        name: "Pantoprazole 40mg",
        manufacturer: "Dr. Reddy's",
        pricePerUnit: 9.0,
        bulkDiscount: "12% off on 200+ units",
        stock: "In Stock",
        expiryDate: "2027-05-05",
        quantity: 1,
        category: "Acid Reflux",
        image: "/images/pantoprazole.jpg",
        offers: {
            type: "Cashback",
            description: "5% cashback on purchases above ₹1000.",
        },
    },
    {
        id: 45,
        name: "Metformin 500mg",
        manufacturer: "Zydus Cadila",
        pricePerUnit: 7.2,
        bulkDiscount: "10% off on 150+ units",
        stock: "In Stock",
        expiryDate: "2026-11-25",
        quantity: 1,
        category: "Diabetes",
        image: "/images/metformin.jpg",
        offers: {
            type: "Flat Discount",
            description: "₹20 off on 3 or more strips.",
        },
    },
    {
        id: 46,
        name: "Dolo 650",
        manufacturer: "Micro Labs",
        pricePerUnit: 6.5,
        bulkDiscount: "5% off on 50+ units",
        stock: "Out of Stock",
        expiryDate: "2026-07-15",
        quantity: 1,
        category: "Fever & Pain",
        image: "/images/dolo650.jpg",
        offers: {
            type: "Combo Offer",
            description: "Buy with ORS pack and get ₹30 off.",
        },
    },
    {
        id: 47,
        name: "Amoxicillin 250mg",
        manufacturer: "Mankind Pharma",
        pricePerUnit: 9.8,
        bulkDiscount: "10% off on 100+ units",
        stock: "In Stock",
        expiryDate: "2027-01-30",
        quantity: 1,
        category: "Antibiotics",
        image: "/images/amoxicillin.jpg",
        offers: {
            type: "Free Delivery",
            description: "Free delivery on orders above ₹500.",
        },
    },
    {
        id: 48,
        name: "Ranitidine 150mg",
        manufacturer: "Abbott",
        pricePerUnit: 4.2,
        bulkDiscount: "10% off on 80+ units",
        stock: "Limited",
        expiryDate: "2026-10-18",
        quantity: 1,
        category: "Acid Reflux",
        image: "/images/ranitidine.jpg",
        offers: {
            type: "Limited Time Offer",
            description: "Flat 15% off this week only!",
        },
    },
    {
        id: 49,
        name: "Cough Syrup (Dextromethorphan)",
        manufacturer: "Himalaya",
        pricePerUnit: 55.0,
        bulkDiscount: "5% off on 20+ bottles",
        stock: "In Stock",
        expiryDate: "2027-04-15",
        quantity: 1,
        category: "Cough & Cold",
        image: "/images/cough_syrup.jpg",
        offers: {
            type: "Buy 3 Get 1 Free",
            description: "Buy 3 bottles and get 1 free.",
        },
    },
    {
        id: 50,
        name: "Calamine Lotion",
        manufacturer: "Himalaya",
        pricePerUnit: 65.0,
        bulkDiscount: "12% off on 50+ units",
        stock: "Limited",
        expiryDate: "2027-02-10",
        quantity: 1,
        category: "Skin Care",
        image: "/images/calamine.jpg",
        offers: {
            type: "Extra Savings",
            description: "Save ₹25 on purchase of 2 bottles.",
        },
    },
    {
        id: 51,
        name: "Ibuprofen 400mg",
        manufacturer: "Torrent Pharma",
        pricePerUnit: 6.0,
        bulkDiscount: "8% off on 100+ units",
        stock: "In Stock",
        expiryDate: "2027-06-20",
        quantity: 1,
        category: "Pain Reliever",
        image: "/images/ibuprofen.jpg",
        offers: {
            type: "Weekend Deal",
            description: "Flat ₹50 off on orders above ₹700 this weekend only.",
        },
    },
    {
        id: 52,
        name: "Losartan 50mg",
        manufacturer: "Lupin",
        pricePerUnit: 9.5,
        bulkDiscount: "10% off on 75+ units",
        stock: "Limited",
        expiryDate: "2026-09-30",
        quantity: 1,
        category: "Blood Pressure",
        image: "/images/losartan.jpg",
        offers: {
            type: "Buy More, Save More",
            description: "Save ₹30 when you buy 5 or more strips.",
        },
    },
    {
        id: 53,
        name: "Aspirin 75mg",
        manufacturer: "Dr. Reddy's",
        pricePerUnit: 4.5,
        bulkDiscount: "12% off on 120+ units",
        stock: "In Stock",
        expiryDate: "2027-02-18",
        quantity: 1,
        category: "Heart Health",
        image: "/images/aspirin.jpg",
        offers: {
            type: "Flat Discount",
            description: "₹10 off on every 3 strips purchased.",
        },
    },
    {
        id: 54,
        name: "Cetirizine 10mg",
        manufacturer: "Alkem Labs",
        pricePerUnit: 3.5,
        bulkDiscount: "7% off on 90+ units",
        stock: "In Stock",
        expiryDate: "2026-11-10",
        quantity: 1,
        category: "Allergy",
        image: "/images/cetirizine.jpg",
        offers: {
            type: "Combo Offer",
            description: "Buy with vitamin C tablets and get ₹20 off.",
        },
    },
    {
        id: 55,
        name: "Omeprazole 20mg",
        manufacturer: "Mankind Pharma",
        pricePerUnit: 7.0,
        bulkDiscount: "10% off on 100+ units",
        stock: "In Stock",
        expiryDate: "2027-03-22",
        quantity: 1,
        category: "Acid Reflux",
        image: "/images/omeprazole.jpg",
        offers: {
            type: "Extra Cashback",
            description: "Get ₹40 cashback on purchases above ₹800.",
        },
    },
    {
        id: 56,
        name: "Dextromethorphan Syrup",
        manufacturer: "Cipla",
        pricePerUnit: 48.0,
        bulkDiscount: "5% off on 30+ bottles",
        stock: "In Stock",
        expiryDate: "2027-05-15",
        quantity: 1,
        category: "Cough & Cold",
        image: "/images/dextromethorphan.jpg",
        offers: {
            type: "Limited Stock Offer",
            description: "Buy before 15th Feb and get ₹25 off per bottle.",
        },
    },
    {
        id: 57,
        name: "Thyroxine 50mcg",
        manufacturer: "Abbott",
        pricePerUnit: 8.0,
        bulkDiscount: "10% off on 200+ units",
        stock: "Limited",
        expiryDate: "2026-12-05",
        quantity: 1,
        category: "Thyroid Health",
        image: "/images/thyroxine.jpg",
        offers: {
            type: "Buy 2 Get ₹20 Off",
            description: "Purchase 2 strips and get ₹20 discount.",
        },
    },
    {
        id: 58,
        name: "Metronidazole 400mg",
        manufacturer: "Sun Pharma",
        pricePerUnit: 6.8,
        bulkDiscount: "10% off on 80+ units",
        stock: "In Stock",
        expiryDate: "2026-08-30",
        quantity: 1,
        category: "Antibiotics",
        image: "/images/metronidazole.jpg",
        offers: {
            type: "Festival Offer",
            description: "Save ₹50 on every purchase above ₹1000 this month.",
        },
    },
    {
        id: 59,
        name: "ORS Hydration Pack",
        manufacturer: "Himalaya",
        pricePerUnit: 32.0,
        bulkDiscount: "5% off on 50+ packs",
        stock: "In Stock",
        expiryDate: "2027-08-15",
        quantity: 1,
        category: "Hydration",
        image: "/images/ors.jpg",
        offers: {
            type: "BOGO (Buy One, Get One 50% Off)",
            description: "Buy 1, get the second one at 50% discount.",
        },
    },
    {
        id: 60,
        name: "Vitamin D3 60k IU",
        manufacturer: "Zydus",
        pricePerUnit: 14.5,
        bulkDiscount: "8% off on 40+ units",
        stock: "Limited",
        expiryDate: "2027-09-10",
        quantity: 1,
        category: "Supplements",
        image: "/images/vitamin_d3.jpg",
        offers: {
            type: "Loyalty Bonus",
            description: "Get extra 5% discount for returning customers.",
        },
    },
    {
        id: 71,
        name: "Rabeprazole + Domperidone",
        manufacturer: "Cipla",
        pricePerUnit: 14.0,
        bulkDiscount: "7% off on 60+ units",
        stock: "In Stock",
        expiryDate: "2027-01-20",
        quantity: 1,
        category: "Acid Reflux",
        image: "/images/rabeprazole.jpg",
        offers: {
            type: "Free Strips",
            description: "Buy 12 strips and get 1 free.",
        },
    },
    {
        id: 72,
        name: "Ibuprofen 400mg",
        manufacturer: "Sun Pharma",
        pricePerUnit: 6.5,
        bulkDiscount: "10% off on 100+ units",
        stock: "Limited",
        expiryDate: "2026-11-05",
        quantity: 1,
        category: "Pain Relief",
        image: "/images/ibuprofen.jpg",
        offers: {
            type: "Buy 2 Get 1 Free",
            description: "Buy 2 bottles and get 1 free.",
        },
    },
    {
        id: 73,
        name: "Cefixime 200mg",
        manufacturer: "Mankind Pharma",
        pricePerUnit: 18.0,
        bulkDiscount: "8% off on 80+ units",
        stock: "In Stock",
        expiryDate: "2027-08-10",
        quantity: 1,
        category: "Antibiotics",
        image: "/images/cefixime.jpg",
        offers: {
            type: "Special Discount",
            description: "Flat ₹50 off on purchases above ₹500.",
        },
    },
    {
        id: 74,
        name: "Calcium + Magnesium Tablets",
        manufacturer: "Abbott",
        pricePerUnit: 20.0,
        bulkDiscount: "5% off on 50+ units",
        stock: "In Stock",
        expiryDate: "2027-05-15",
        quantity: 1,
        category: "Supplements",
        image: "/images/calcium_magnesium.jpg",
        offers: {
            type: "Loyalty Bonus",
            description: "Buy 5 packs, get ₹100 cashback.",
        },
    },
    {
        id: 75,
        name: "Cetirizine 10mg",
        manufacturer: "Dr. Reddy's",
        pricePerUnit: 3.5,
        bulkDiscount: "7% off on 120+ units",
        stock: "In Stock",
        expiryDate: "2027-07-30",
        quantity: 1,
        category: "Allergy",
        image: "/images/cetirizine.jpg",
        offers: {
            type: "Festival Special",
            description: "Flat ₹20 off on purchases above ₹300.",
        },
    },
    {
        id: 76,
        name: "Vitamin C Chewable Tablets",
        manufacturer: "GSK",
        pricePerUnit: 25.0,
        bulkDiscount: "9% off on 40+ units",
        stock: "Limited",
        expiryDate: "2026-12-25",
        quantity: 1,
        category: "Supplements",
        image: "/images/vitamin_c.jpg",
        offers: {
            type: "Combo Offer",
            description: "Buy with Vitamin D3 and get ₹30 off.",
        },
    },
    {
        id: 77,
        name: "Aspirin 75mg",
        manufacturer: "Zydus",
        pricePerUnit: 5.0,
        bulkDiscount: "6% off on 90+ units",
        stock: "In Stock",
        expiryDate: "2027-06-20",
        quantity: 1,
        category: "Blood Thinner",
        image: "/images/aspirin.jpg",
        offers: {
            type: "Stock Clearance",
            description: "Flat ₹75 off on orders above ₹1500.",
        },
    },
    {
        id: 78,
        name: "Dextromethorphan Cough Syrup",
        manufacturer: "Himalaya",
        pricePerUnit: 55.0,
        bulkDiscount: "5% off on 20+ bottles",
        stock: "In Stock",
        expiryDate: "2027-09-10",
        quantity: 1,
        category: "Cough & Cold",
        image: "/images/dextromethorphan.jpg",
        offers: {
            type: "Extra Free",
            description: "Buy 3 bottles, get 1 extra free.",
        },
    },
    {
        id: 79,
        name: "Metformin 500mg",
        manufacturer: "Alkem Labs",
        pricePerUnit: 12.5,
        bulkDiscount: "8% off on 100+ units",
        stock: "Limited",
        expiryDate: "2027-11-05",
        quantity: 1,
        category: "Diabetes",
        image: "/images/metformin.jpg",
        offers: {
            type: "Bulk Saver",
            description: "Flat ₹100 off on orders above ₹2500.",
        },
    },
    {
        id: 80,
        name: "Hydroxyzine 25mg",
        manufacturer: "Lupin",
        pricePerUnit: 9.5,
        bulkDiscount: "6% off on 80+ units",
        stock: "In Stock",
        expiryDate: "2027-03-15",
        quantity: 1,
        category: "Anxiety & Sleep",
        image: "/images/hydroxyzine.jpg",
        offers: {
            type: "Free Strips",
            description: "Buy 10 strips, get 1 free.",
        },
    },
];















